### ISSUE TITLE
代码参考文献

### ISSUE THREAD

**Issue by wenchao-zhao** [ClayLiu/Swarm-intelligence-optimization-algorithm#1]
你好，请问有没有SSA框架的参考文献呢，如果使用SSA框架求解多目标问题应该是那些代码呢？谢谢你

**Comment by ClayLiu** [comment]
我这里实现的只有单目标的，关于 SSA 你可以参考这篇文章，Salp Swarm Algorithm: A bio-inspired optimizer for engineering
design problems 第一作者是 Seyedali Mirjalili
